### ISSUE TITLE
Failed - Error:  401

### ISSUE THREAD

**Issue by pengfei123xiao** [shreybatra/Twitter-Stream-API-Dataset#28]
Hi Shreybatra,

I am following the instructions to test this script, with a MongoDB client running and my own Twitter API key given.
I tried to test the first endpoint with '/triggertweets?keyword=Australia', the webpage shows '{"trigger":"started"}', however, the Pycharm come up with error infomation: 'Failed - Error:  401'.
Do you know why this happened?

Many thanks.
Best regard.

**Comment by shreybatra** [comment]
Hii @prodigyxiao, could you share the stack trace of the error in your pycharm console?

**Comment by pengfei123xiao** [comment]
(venv) C:\Users\Xiao Pengfei\PycharmProjects\Twitter-Stream-API-Dataset-master>python streamtest.py
 * Serving Flask app "streamtest" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Restarting with stat
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [09/Mar/2019 15:05:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [09/Mar/2019 15:05:58] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [09/Mar/2019 15:08:12] "GET /triggertweets?keyword=Australia HTTP/1.1" 200 -
Failed - Error:  401
Failed - Error:  401
Failed - Error:  401

Hi Shreybatra,
There is no stack trace info in the console, only continuously reminds that 'Failed - Error:  401'.

**Comment by shreybatra** [comment]
@prodigyxiao Thankyou, just let me check.

**Comment by shreybatra** [comment]
@prodigyxiao Looks like version 3.6.0 was not supported by the API anymore. I have updated the file with latest authentication measure. Please pull the changes/clone it again. Also, the output ```{ "trigger" : "started" }``` would arise as currently there is no check to see if the documents have successfully been inserted. Check your console for a **success** output instead of Forbidden. Also regenerate your Auth tokens in Twitter Developer console and use the new tokens in the code.

**Comment by pengfei123xiao** [comment]
Thank you very much!

**Comment by shreybatra** [comment]
@prodigyxiao Is everything okay now? Should I close this issue?

**Comment by pengfei123xiao** [comment]
Sorry, Shreybatra.
Things do not go well in my PC.
I have updated the requirement file, py script and the API key, but this time I cannot even go the the 'triggertweets' page.
And the 401 error still exists.

**Comment by shreybatra** [comment]
@prodigyxiao updated? Let's delete the whole folder you have and start again....
1. Clone/Download the repository.
2. Go into the Project directory via CMD/Terminal.
3. Run command ```pip install -r requirements.txt```
4. Check that tweepy version 3.7.0 has been installed in your computer via the output of step 3.
5. Now run the file ```python streamtest.py```. Server should be started in your terminal.
6. Visit endpoints.

Remember it supports only python 3 version greater or equal to 3.5.2.
If any error persists, do share the screenshot/stack trace.

Note - 401 error is due to unauthorised Twitter API, and the endpoint "triggertweets" will not show an output till it gets a successful output.

**Comment by pengfei123xiao** [comment]
Thank you very much for your patient explanation!!!

**Comment by pengfei123xiao** [comment]
Oh, it works!
Thank you very much!
Have a lovely weekend!
Cheers!

**Comment by shreybatra** [comment]
Great..! 👍  Thankyou
